// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanDoCongNghe.Data;

#nullable disable

namespace WebBanDoCongNghe.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260323091531_Add30ProductsSeeder")]
    partial class Add30ProductsSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanDoCongNghe.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Laptop Gaming & Văn phòng",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Điện thoại thông minh",
                            Name = "SmartPhone"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chuột, Bàn phím, Tai nghe",
                            Name = "Phụ kiện"
                        });
                });

            modelBuilder.Entity("WebBanDoCongNghe.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebBanDoCongNghe.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WebBanDoCongNghe.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Apple",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3327),
                            Name = "MacBook Pro 16\" M3 Max",
                            Price = 59990000m,
                            Specifications = "M3 Max, 36GB RAM, 1TB SSD, 120Hz",
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Dell",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3622),
                            Name = "Dell XPS 15 Plus",
                            Price = 45990000m,
                            Specifications = "Intel Core i9, RTX 4080, 32GB RAM, 1TB SSD",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 3,
                            Brand = "ASUS",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3624),
                            Name = "ASUS ROG Zephyrus G16",
                            Price = 54990000m,
                            Specifications = "Intel i9, RTX 4090, 32GB RAM, 2TB SSD",
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Lenovo",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3625),
                            Name = "Lenovo ThinkPad X1 Carbon",
                            Price = 38990000m,
                            Specifications = "Intel i7, 16GB RAM, 512GB SSD, 14\" OLED",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 5,
                            Brand = "HP",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3627),
                            Name = "HP Pavilion 15",
                            Price = 22990000m,
                            Specifications = "AMD Ryzen 7, RTX 4050, 16GB RAM, 512GB SSD",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 6,
                            Brand = "MSI",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3639),
                            Name = "MSI GE66 Raider",
                            Price = 48990000m,
                            Specifications = "Intel i9, RTX 4080, 32GB RAM, 1TB SSD, 240Hz",
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Acer",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3641),
                            Name = "Acer Swift 3",
                            Price = 24990000m,
                            Specifications = "AMD Ryzen 5, 16GB RAM, 512GB SSD, 13.3\" FHD",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Razer",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3642),
                            Name = "Razer Blade 16",
                            Price = 60990000m,
                            Specifications = "Intel i9, RTX 4090, 32GB RAM, 2TB SSD, 16\" 240Hz",
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 9,
                            Brand = "LG",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3644),
                            Name = "LG Gram 17Z90",
                            Price = 39990000m,
                            Specifications = "Intel Core Ultra, 32GB RAM, 1TB SSD, 2.59kg",
                            StockQuantity = 11
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Samsung",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3646),
                            Name = "Samsung Galaxy Book3 Pro",
                            Price = 35990000m,
                            Specifications = "Intel i7, 16GB RAM, 512GB SSD, 14\" AMOLED",
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Apple",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3666),
                            Name = "iPhone 15 Pro Max",
                            Price = 32990000m,
                            Specifications = "A17 Pro, 256GB, 6.7\", Titanium",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Samsung",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3668),
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 29990000m,
                            Specifications = "Snapdragon 8 Gen 3, 256GB, 6.8\", 200MP",
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Google",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3670),
                            Name = "Google Pixel 8 Pro",
                            Price = 27990000m,
                            Specifications = "Tensor G3, 128GB, 6.7\", AI Magic Eraser",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 14,
                            Brand = "OnePlus",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3672),
                            Name = "OnePlus 12",
                            Price = 20990000m,
                            Specifications = "Snapdragon 8 Gen 3, 256GB, 6.7\", 120Hz",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Xiaomi",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3673),
                            Name = "Xiaomi 14 Ultra",
                            Price = 18990000m,
                            Specifications = "Snapdragon 8 Gen 3, 512GB, 6.73\", Leica Camera",
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Oppo",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3675),
                            Name = "Oppo Find X7",
                            Price = 19990000m,
                            Specifications = "Snapdragon 8 Gen 3, 256GB, 6.78\", 50MP",
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Vivo",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3676),
                            Name = "Vivo X100 Pro",
                            Price = 17990000m,
                            Specifications = "Snapdragon 8 Gen 3, 512GB, 6.78\", Zeiss Camera",
                            StockQuantity = 32
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Honor",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3680),
                            Name = "Honor 200 Pro",
                            Price = 15990000m,
                            Specifications = "Snapdragon 8 Gen 3, 256GB, 6.78\", 200MP",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Nothing",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3682),
                            Name = "Nothing Phone 2",
                            Price = 12990000m,
                            Specifications = "Snapdragon 8+ Gen 1, 256GB, 6.7\", Glyph",
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Motorola",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3684),
                            Name = "Motorola Edge 50 Pro",
                            Price = 16990000m,
                            Specifications = "Snapdragon 8 Gen 3, 512GB, 6.7\", Hasselblad",
                            StockQuantity = 38
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Apple",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3704),
                            Name = "Apple AirPods Pro Max",
                            Price = 13990000m,
                            Specifications = "Noise Cancellation, 20h Battery, Spatial Audio",
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Sony",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3705),
                            Name = "Sony WH-1000XM5",
                            Price = 9990000m,
                            Specifications = "ANC, 30h Battery, Hi-Res Audio",
                            StockQuantity = 24
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Logitech",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3707),
                            Name = "Logitech G502 HERO",
                            Price = 1990000m,
                            Specifications = "25600 DPI, RGB, Gaming Mouse",
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Corsair",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3708),
                            Name = "Corsair K95 Platinum",
                            Price = 4990000m,
                            Specifications = "Mechanical, Cherry MX, RGB",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Samsung",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3711),
                            Name = "Samsung Buds3",
                            Price = 3990000m,
                            Specifications = "ANC, 360 Audio, 26h with case",
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 26,
                            Brand = "JBL",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3713),
                            Name = "JBL Flip 6",
                            Price = 2990000m,
                            Specifications = "Portable Speaker, 12h Battery, IP67",
                            StockQuantity = 42
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Razer",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3714),
                            Name = "Razer DeathAdder V3",
                            Price = 2490000m,
                            Specifications = "30000 DPI, Wireless, Gaming Mouse",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 28,
                            Brand = "SteelSeries",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3716),
                            Name = "SteelSeries Arctis Pro",
                            Price = 5990000m,
                            Specifications = "Hi-Fi Audio, Wireless, Gaming Headset",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Anker",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3718),
                            Name = "Anker PowerBank 737",
                            Price = 1990000m,
                            Specifications = "140W, 41600mAh, Fast Charging",
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Belkin",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 3, 23, 16, 15, 27, 648, DateTimeKind.Local).AddTicks(3720),
                            Name = "Belkin Magnetic Wireless Charger",
                            Price = 1290000m,
                            Specifications = "15W MagSafe, Fast Charging, Foldable",
                            StockQuantity = 55
                        });
                });

            modelBuilder.Entity("WebBanDoCongNghe.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebBanDoCongNghe.Models.Order", b =>
                {
                    b.HasOne("WebBanDoCongNghe.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanDoCongNghe.Models.OrderDetail", b =>
                {
                    b.HasOne("WebBanDoCongNghe.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanDoCongNghe.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanDoCongNghe.Models.Product", b =>
                {
                    b.HasOne("WebBanDoCongNghe.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebBanDoCongNghe.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebBanDoCongNghe.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
